python runmacro.py 0 8 "datalists/2f_Z_bhabhag.list" "tree" "BHAg" "eventSelTau.root" "RECREATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/2f_Z_hadronic.list" "tree" "ZHAD" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/2f_Z_leptonic.list" "tree" "ZL" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/4f_singleW_leptonic.list" "tree" "WL" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/4f_singleW_semileptonic.list" "tree" "WS" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/4f_singleZee_leptonic.list" "tree" "ZEEL" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/4f_singleZee_semileptonic.list" "tree" "ZEES" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/4f_singleZnunu_leptonic.list" "tree" "ZNUL" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/4f_singleZnunu_semileptonic.list" "tree" "ZNUS" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/4f_WW_hadronic.list" "tree" "WWHAD" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"

python runmacro.py 0 8 "datalists/4f_WW_leptonic.list" "tree" "WWL" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/4f_WW_semileptonic.list" "tree" "WWS" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/4f_ZZ_hadronic.list" "tree" "ZZHAD" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/4f_ZZ_leptonic.list" "tree" "ZZL" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/4f_ZZ_semileptonic.list" "tree" "ZZS" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"

python runmacro.py 0 8 "datalists/eeH.list" "tree" "EEH" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/mumuH.list" "tree" "MUH" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/tautauH.list" "tree" "TAUH" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/qqH.list" "tree" "QQH" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/nunuH.list" "tree" "NNH" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"

python runmacro.py 0 8 "datalists/4f_singleZsingleWMix_leptonic.list" "tree" "ZWML" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/4f_ZZWWMix_hadronic.list" "tree" "ZZWWH" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/4f_ZZWWMix_leptonic.list" "tree" "ZZWWL" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/6f_eeWW.list" "tree" "EEWW" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/6f_llWW.list" "tree" "LLWW" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/6f_ttbar.list" "tree" "TTB" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/6f_vvWW.list" "tree" "VVWW" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/6f_xxWW.list" "tree" "XXWW" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/6f_xxxxZ.list" "tree" "XXZ" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"
python runmacro.py 0 8 "datalists/6f_yyyyZ.list" "tree" "YYZ" "eventSelTau.root" "UPDATE" "-0.8" "0.3" "1600"

